### ISSUE TITLE
New portal edits - /login/teacher

### ISSUE THREAD

**Issue by lauracumming** [ocadotechnology/codeforlife-portal-react#105]
- [x] Colour check - change from primary 500 to 400
- [x] Add in more padding and margin to page (apply to all login pages)
- [x] Reduce size of shapes by 10%
- [x] H5 looks a little large 
- [x] Both text fields should have an icon if adding - to match to rest of website

**Comment by SKairinos** [comment]
https://development-portal-dot-decent-digit-629.appspot.com/login/teacher

**Comment by lauracumming** [comment]
I think the footer has been changed to 400 too? @cewei8483 I just meant the page elements - if you look at the existing portal, the shapes are 400, and the footer is 500. @SKairinos
