### ISSUE TITLE
teacher teach - reset password and login link

### ISSUE THREAD

**Issue by lauracumming** [ocadotechnology/codeforlife-portal-react#161]
## Task Description

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaEJwIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--059493820ed9f1e2a5d8206e114c3903b1bbc909/image.png)

Implement the endpoint for the Reset password and login link button in the students table. Make sure the popup shows and that the endpoint can handle one or multiple students (should be the same as current logic).
On submission, the teacher is redirected to the page which generates the login details, reminder cards and direct login links for the students so the endpoint should allow for that functionality too (depending on the order, this functionality may have already been implemented in #163).

**Comment by faucomte97** [comment]
No longer relevant.
