### ISSUE TITLE
teacher teach - add students to class

### ISSUE THREAD

**Issue by lauracumming** [ocadotechnology/codeforlife-portal-react#163]
## Task Description

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdTltIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--fe633eaaa61b09fb22c1e611769fe87d30451799/image.png)

Implement the endpoint for the add students form for a specific class. Allows import from CSV or just typing directly in the box.
Submitting the form redirects to the page which shows the login options for the students. That page also allows the generation of the login cards as well as the direct login URLs, please ensure this is included in this task.

**Comment by faucomte97** [comment]
No longer relevant.
