### ISSUE TITLE
teacher teach - level control for a class

### ISSUE THREAD

**Issue by lauracumming** [ocadotechnology/codeforlife-portal-react#166]
## Task Description

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdXRtIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--3a22dc40969dd916399d4d1ff34107f57a7acad0/image.png)

Implement the endpoint for the level control form. The logic should be purely the same as the current production site.
Submitting the form currently redirects the teacher to the School tab with a banner confirming success, but we could change the redirect to stay in the selected class page if we prefer.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdXhtIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--a29b7f554087893460e1e384e11f899048b3165c/image.png)

**Comment by faucomte97** [comment]
Duplicate task.
