### ISSUE TITLE
transfer school flow

### ISSUE THREAD

**Issue by SKairinos** [ocadotechnology/codeforlife-portal-react#188]
Currently, there's no flow to handle teachers switching from one school to another. The short-term fix is for teachers to delete their account and recreate them.

Rather, if a teacher is invited to another school, upon accepting the invite, the teacher should be informed that they're leaving their current school to join another school. The teacher should be warned of the consequences of leaving their current school.

If the teacher is the only teacher in the school, they should be warned that leaving the school will result in the permanent deletion of that school.

Else if there are other teachers in the school and the current teacher is an admin, at least one of the other teachers MUST be an admin before the current admin leaves. Block transferring schools until this constraint is satisfied.

**Comment by SKairinos** [comment]
@lauracumming commented:
"I think we already warn teachers about them being the only admin if they leave. Would need to check."

**Comment by lauracumming** [comment]
Yes, we do

**Comment by lauracumming** [comment]
I think this is a research task rather than dev. I'll create a research task for it to test this hypothesis

**Comment by faucomte97** [comment]
Closing until researched further.
