### ISSUE TITLE
copy and paste the new SSO service

### ISSUE THREAD

**Issue by lauracumming** [ocadotechnology/codeforlife-portal-react#192]
Until the circular dependencies are broken, all future development of the SSO service will happen on this copy.

**Comment by SKairinos** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Code-for-Life-Development--56f2afba6e54555c586f6db3/issues/ocadotechnology/codeforlife-portal-react/192?planning-poker) with Zenhub @SKairinos @faucomte97
