### ISSUE TITLE
Portal email templates

### ISSUE THREAD

**Issue by faucomte97** [ocadotechnology/codeforlife-portal-react#223]
We need to transfer all of our in-code email templates that are currently being sent via AWS' Simple Email Service to Dotditigtal as triggered email campaigns.

A generic email template should first be established on Dotdigital. This email template will be used to create all/most of the email templates in this epic.

Relevant files:
- https://github.com/ocadotechnology/codeforlife-portal/blob/master/cfl_common/common/helpers/emails.py
- https://github.com/ocadotechnology/codeforlife-portal/blob/master/portal/templates/portal/email_style_template.html
- https://github.com/ocadotechnology/codeforlife-portal/blob/master/portal/templates/email.html
- https://github.com/ocadotechnology/codeforlife-portal/blob/master/portal/views/cron/user.py

**Comment by SKairinos** [comment]
I suggest we send an email to users when they are auto-deleted after 19 days of not verifying their account.
