### ISSUE TITLE
Teacher revoked admin email

### ISSUE THREAD

**Issue by faucomte97** [ocadotechnology/codeforlife-portal-react#232]
This is the email sent to teachers when they are unmade a school-admin.

**Comment by SKairinos** [comment]
Subject and email copy are contradicting. Suggest changing the subject to "You're account permissions have been updated"
<img width="720" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL3pVQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--65f070acbcc59835167a9d6e8dca559d42812cdb/image_720.png" alt="image_720.png" />

**Comment by evemartin** [comment]
Yes, I have changed it on this email and also on the email where a teacher is given admin access!
