### ISSUE TITLE
New About us page edits

### ISSUE THREAD

**Issue by lauracumming** [ocadotechnology/codeforlife-portal-react#81]
- [x] Increase sub header size in banner

![Screenshot 2023-06-30 at 17.05.16.png](https://images.zenhubusercontent.com/5da58aa016098c0001fb85d1/978d3422-ea89-497e-b533-8852668d80bc)

- [x] Increase padding above text in sections so padding is equal top and bottom
![Screenshot 2023-06-30 at 17.06.25.png](https://images.zenhubusercontent.com/5da58aa016098c0001fb85d1/521bc4a9-3312-4dd5-9dc1-80e9a444b1ed)

- [x] Increase weight of font for quotes (presumably the same as index page)

![Screenshot 2023-06-30 at 17.08.53.png](https://images.zenhubusercontent.com/5da58aa016098c0001fb85d1/1983946c-27ce-438d-9929-daeaaa997a3b)

- [x] Increase margin between columns  
![Screenshot 2023-06-30 at 17.15.16.png](https://images.zenhubusercontent.com/5da58aa016098c0001fb85d1/e5a653df-d850-4933-987d-71da8e2043ca)

- [x] Check body text is same dark grey as header - it is difficult to read - needs to be darker or heavier
![Screenshot 2023-06-30 at 17.15.08.png](https://images.zenhubusercontent.com/5da58aa016098c0001fb85d1/ec5b6115-70cb-4012-83eb-68f92aae7118)

- [x] Ensure line spacing consistent between headers and body
![Screenshot 2023-06-30 at 17.12.42.png](https://images.zenhubusercontent.com/5da58aa016098c0001fb85d1/23523208-e1b0-44bf-9366-c1d5649cd73e)

**Comment by SKairinos** [comment]
https://development-portal-dot-decent-digit-629.appspot.com/about-us
