### ISSUE TITLE
New portal edits - /teacher/dashboard/school

### ISSUE THREAD

**Issue by lauracumming** [ocadotechnology/codeforlife-portal-react#83]
- [x] Greys in the table need matching to the grey on the existing site - header and body cells
- [x] Padding as on other pages needs increasing to give 'breathing' space

**Comment by lauracumming** [comment]
Could I get the hyperlink please? @KamilPawel

**Comment by cewei8483** [comment]
https://development-portal-dot-decent-digit-629.appspot.com/teacher/dashboard/school
