### ISSUE TITLE
New portal edits - teacher/backupToken

### ISSUE THREAD

**Issue by lauracumming** [ocadotechnology/codeforlife-portal-react#86]
Same as other login screens:

- [x] padding (add)
- [x] font size (reduce)
- [x] icons (please add to password field too)
- [x] Shape size - reduce by 10%

**Comment by lauracumming** [comment]
Could I get the hyperlink please @KamilPawel @cewei8483

**Comment by cewei8483** [comment]
https://development-portal-dot-decent-digit-629.appspot.com/login/teacher/backup-token
