### ISSUE TITLE
New portal edits - /student/dashboard/independent/join

### ISSUE THREAD

**Issue by lauracumming** [ocadotechnology/codeforlife-portal-react#87]
- [x] Add padding above button
![Screenshot 2023-07-15 at 10.48.00.png](https://images.zenhubusercontent.com/5da58aa016098c0001fb85d1/cda9f50c-488d-4704-8aeb-95bc2a771af8)

**Comment by SKairinos** [comment]
https://development-portal-dot-decent-digit-629.appspot.com/student/dashboard/independent/join
