### ISSUE TITLE
New portal edits -  /student/dashboard/independent/account

### ISSUE THREAD

**Issue by lauracumming** [ocadotechnology/codeforlife-portal-react#88]
- [x] Add padding before buttons in these sections

![Screenshot 2023-07-15 at 10.46.21.png](https://images.zenhubusercontent.com/5da58aa016098c0001fb85d1/3ec33f53-ba64-42d9-abfb-6f79d5dd50a6)![Screenshot 2023-07-15 at 10.46.12.png](https://images.zenhubusercontent.com/5da58aa016098c0001fb85d1/cb2b0d81-2f93-4249-a01f-007723502ac8)

**Comment by SKairinos** [comment]
https://development-portal-dot-decent-digit-629.appspot.com/student/dashboard/independent/account
