### ISSUE TITLE
New portal edits - /student/dashboard/independent

### ISSUE THREAD

**Issue by lauracumming** [ocadotechnology/codeforlife-portal-react#89]
Are we missing an animation or is it just not loading for me?

**Comment by cewei8483** [comment]
Looks fine to me.

**Comment by SKairinos** [comment]
Our Content Service Provider (CSP) settings haven't whitelisted the video's source so our site is refusing to trust and load the video. We're currently whitelisting it now.

**Comment by faucomte97** [comment]
@SKairinos Content Security Policy*
