### ISSUE TITLE
New portal edits - /student/dashboard/dependent/account

### ISSUE THREAD

**Issue by lauracumming** [ocadotechnology/codeforlife-portal-react#90]
- [x] Add in some padding to give it air
![Screenshot 2023-07-15 at 10.42.40.png](https://images.zenhubusercontent.com/5da58aa016098c0001fb85d1/12a5bd49-5d9d-4902-ae6e-a5b8431ee9d4)

**Comment by SKairinos** [comment]
https://development-portal-dot-decent-digit-629.appspot.com/student/dashboard/dependent/account
