### ISSUE TITLE
New portal edits -  /student

### ISSUE THREAD

**Issue by lauracumming** [ocadotechnology/codeforlife-portal-react#91]
- [x] Just padding again on this page between elements - increase
- [x] Top and bottom of sections - increase and make same as other pages

![Screenshot 2023-07-15 at 10.35.15.png](https://images.zenhubusercontent.com/5da58aa016098c0001fb85d1/f8f3e67e-1429-4cae-bc84-6050c654b071)
![Screenshot 2023-07-15 at 10.35.37.png](https://images.zenhubusercontent.com/5da58aa016098c0001fb85d1/ef8d98ba-f6d8-4832-be52-323845a35e21)![Screenshot 2023-07-15 at 10.35.46.png](https://images.zenhubusercontent.com/5da58aa016098c0001fb85d1/5d43276e-d88f-46c2-987a-efc3d6549007)

**Comment by cewei8483** [comment]
https://development-portal-dot-decent-digit-629.appspot.com/student

**Comment by lauracumming** [comment]
✅
