### ISSUE TITLE
New portal edits - /teacher/dashboard/account

### ISSUE THREAD

**Issue by lauracumming** [ocadotechnology/codeforlife-portal-react#93]
- [x] Add padding throughout (check existing site)
![Screenshot 2023-07-15 at 10.27.18.png](https://images.zenhubusercontent.com/5da58aa016098c0001fb85d1/dc8c4e23-ffae-42d4-9447-80bc31f516fc)

**Comment by SKairinos** [comment]
@cewei8483 align the padding to look like this.
![image.png](https://images.zenhubusercontent.com/63ed10d0c8cb61b145ebeb5c/edbc6bff-3f80-4234-8366-588820ee0c7a)

Also, keep in mind that:
1. if the user doesn't have 2fa enabled: only the "Setup two factor authentication" button will show
2. if they user does have 2fs enabled: the setup button is replaced with the Backup tokens and disable 2fa sub sections.

**Comment by cewei8483** [comment]
https://development-portal-dot-decent-digit-629.appspot.com/teacher/dashboard/account

**Comment by lauracumming** [comment]
✅
