### ISSUE TITLE
New portal edits - password /reset-password/independent

### ISSUE THREAD

**Issue by lauracumming** [ocadotechnology/codeforlife-portal-react#97]
- [ ] same reduction to shapes as other login pages
- [ ] same adjustments to padding - increase
- [ ] same adjustments to buttons - alignment

**Comment by SKairinos** [comment]
https://development-portal-dot-decent-digit-629.appspot.com/reset-password/independent

**Comment by lauracumming** [comment]
All of the pages with coloured shapes on need to be 400 and the footer 500 please
